# Generated by Django 2.2 on 2020-08-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SemiRestful_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Semirestful',
            new_name='TV_show',
        ),
    ]
